# Generated by Django 5.0.4 on 2024-05-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_topic_article_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='opening',
            field=models.TextField(default='no_opening'),
            preserve_default=False,
        ),
    ]
